version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_microcommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: microcommerce
    restart: always

  redis:
    image: redis:latest
    container_name: redis_microcommerce
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_microcommerce
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka_microcommerce
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_microcommerce:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka_microcommerce:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

volumes:
  mongo_data:
