version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_microcommerce
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productdb
    restart: always
