version: '3.8'

services:
  mongodb: #product, user, order, cart, payment
    image: mongo:6.0
    container_name: mongo_microcommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: microcommerce
    restart: always

  redis: #cache products, login, session
    image: redis:latest
    container_name: redis_microcommerce
    ports:
      - "6379:6379"
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper_microcommerce
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka:
    image: bitnami/kafka:3.5.0
    container_name: kafka_microcommerce
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_microcommerce:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 #how kafka will listen for connections
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
    depends_on:
      - zookeeper
    restart: always

  product-service:
    build:
      context: .            
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  mongo_data:
