server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo_microcommerce
      port: 27017
      database: productdb 
    redis:
      host: redis_microcommerce
      port: 6379
  cache:
    type: redis
