server:
  port: 8080

spring:
  data:
    mongodb:
      host: mongo_microcommerce
      port: 27017
      database: productdb 
    redis:
      host: redis_microcommerce
      port: 6379
  cache:
    type: redis

logging:
  level:
    org.springframework: INFO
    com.bread.productservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/product-service.log